### PR TITLE
Fix converting solution generated by cmake 3.15

### PR DESCRIPTION
**Pull request by niktischenko**

### CODE REVIEW

**Comment by mapron** [comment]
Changes are good, just have one question.

**Comment by niktischenko** [comment]
So.. what is the question?

**Comment by mapron** [comment]
I asked a question in a "ui files ignoring" commit. 
Quotation:
"So I guess without this change, ui files were ignored and did not participate in build, right?"

**Comment by niktischenko** [comment]
> "So I guess without this change, ui files were ignored and did not participate in build, right?"

Absolutely :)

**Pull request merged**
